Repository mdflynn/ideabox-boilerplate, pull requests merged in 2020-07, with the labels that each got.

#1 Create initial mobile HTML
  index.html
Labels: enhancement

#2 Aligned header menu and title text
  assets/comment.svg
  assets/delete-active.svg
  assets/delete.svg
  assets/downvote-active.svg
  assets/downvote.svg
  assets/menu-close.svg
  assets/menu.svg
  assets/search.svg
  assets/star-active.svg
  assets/star.svg
  assets/upvote-active.svg
  assets/upvote.svg
  index.html
  styles.css
Labels: enhancement

#3 Feature/form formatting and alignment
  index.html
  styles.css
Labels: enhancement

#4 Feature/search bar styling
  index.html
  styles.css
Labels: enhancement

#5 Addition of Idea Cards and dropdown menu area.
  index.html
  styles.css
Labels: enhancement

#6 Feature/form input fields dc
  index.html
  styles.css
Labels: enhancement

#7 Add Normalize.css file and styling edits
  index.html
  normalize.css
  styles.css
Labels: enhancement

#8 Add a new readme file and retain the given readme file me.
  GivenREADME.md
  README.md
Labels: documentation, enhancement

#10 Feature/correct search bar
  styles.css
Labels: enhancement

#11 Fix/update css dc
  styles.css
Labels: enhancement

#12 Feature/begin js build
  index.html
  src/idea.js
  src/main.js
Labels: enhancement

#13 Feature/continue js build user journeys
  index.html
  src/idea.js
  src/main.js
  styles.css
Labels: bug, enhancement

#14 Feature/remove from view dc
  index.html
  src/main.js
  styles.css
Labels: bug, enhancement

#15 Feature/tweaking html css and js flow
  src/idea.js
  src/main.js
Labels: enhancement

#16 Feature/add updated readme dc
  README.md
  index.html
  styles.css
Labels: documentation, enhancement

#17 Feature/troubleshoot persisting html js
  index.html
  src/main.js
  styles.css
Labels: enhancement
